### ISSUE TITLE
File upload missing current_byte_position parameter

### ISSUE THREAD

**Issue by coleshaw** [mountetna/metis#61]
Running Metis on latest master (986c76e1201297e63aaf06a64484772ae3aca095), I get an error trying to upload a file via the browser:

POST to https://metis-dev.etna-development.org/ipi/upload/TestBucket/<file name + headers>

Leads to a 422:

```
{"error":"Missing param current_byte_position"}
```

Sent params were:

```
-----------------------------58833755134078827354081713951
Content-Disposition: form-data; name="action"

blob
-----------------------------58833755134078827354081713951
Content-Disposition: form-data; name="blob_data"; filename="blob"
Content-Type: application/octet-stream

PNG


IHDRÜ
Z%¸âHiCCPICC ProfileHWXSÉ[RIhH	½"HBT©J	AÄî²¨àÚElè¢«+ kE]ë"Ø]ËÃÊÊºX°¡ò&ÖÕï½÷½ó}sï3çü§dî½3èÔð¤Ò\T<I,><5)5Ez`ðør);..
@ºÿSÞ\ÖP®¸(¹¾ÿ¯¢'Êù qgäü</áKe½¡ÞzfT§@l 	B,Uâ,5.Qâ5®TÙ$Æs Þ
ÆãÉ²ÐnzV!?òhßØU"KÐ!CÀñG@<*/oC;àñOÖ?839y¼¬a¬®E%ä±\Ëõ¶ãK^®b(4,"^Y3ìÛÍJL¸W±>ÄïÄ=Ä(U¤HRÛ£¦|9ö0!vðB"!68L¥ÑgdÃ¸Ã¸ß%Byh³F6#>vgÊ8lo#O¦«´?¥ÈIbkøoÜ!þ×Å¢ÄuÎµP±6ÄLyNB¤Ú³)qbldxeþ6û
%áÁj~lZ¦,,^c/ËÕ-¹1\U JÐðìæóTùAÜ"°xòIQCµ!¡êÚ±¡$IS/Ö%-×ø¾æÆiìqª07\©·ØT^ ñÅ
àTóã1Ò¸DuxF6oB:¼D, #ÌÙ@ÜÞÛÜ©gÂÈ@fÈ#E5#×PþHäÃ~ÁªY!(úOÃZõÕdªfU9à1Äy äÂß
d8Z2x5âo¢óa®¹p(ç¾Õ±¡&J£Qñ²t,¡Äb1èà¸¯Ap¸áÞ¸ÏP¶Û:	×][ÓÅd_ÕÃÑ FÓÔñeÍ¸dõÀqÈ¹q&n\ðq0±= £É\Yý×Üÿ¨á®kì(®2DqøÚSÛIÛcEÙÓ/;¤Î5c¸¯á¯ãs¾è´Þ#¿¶Ä`°3Ø	ìvk,ìÖ]Ä(ñð*z¤ZECÑâUùä@ñ7ñxÊNÊ]\{\?ªç
EÊ÷#àÌÎ³D,6|óY\	ô(«+Êïú5õ©ú> ÌóëòàSYëxÖzãÍß:ëðñX	À¾BV¨ÖáÊP|¢9°°
-----------------------------58833755134078827354081713951
Content-Disposition: form-data; name="next_blob_size"

1024
-----------------------------58833755134078827354081713951
Content-Disposition: form-data; name="next_blob_hash"

171a5b3ced40ce3d59050ff2bd70be04
-----------------------------58833755134078827354081713951--
```

Wonder if this is an issue on just the first chunk? Will investigate. Upload worked fine for me on the code included with the VM, before pulling down the latest code. Am running on migration  version 18.

**Comment by graft** [comment]
How fresh is your javascript? If you haven't rebuilt the client, it might be using an outdated request format.

**Comment by coleshaw** [comment]
In the VM, I don't seem to need to build the JavaScript? At least, there are no explicit `.js` files anywhere (in any of the projects), even though the UIs all work, and when I change a `.jsx` file, Puma / Rack seem to pick it up automagically...does that make sense, or did I skip a step? I tried running `npm run build`, but it didn't like the paths in `package.json` because they don't include `lib/` in the paths.

**Comment by coleshaw** [comment]
Refreshing the JS seemed to help, with:

```
./node_modules/webpack/bin/webpack.js --env.NODE_ENV=development
```

So I think this issue is closed. Will keep the PR open to update `package.json` and update documentation.
